# -*- coding: utf-8 -*-
"""AI & ML 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmdwBC_tiCxTDnsc3q8rhEiLPap44CWS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('ecommerce_sales_forecast_dataset.csv')

# Preview
df.head()

print("Columns in dataset:")
print(df.columns)

if 'Date' not in df.columns:
    df['Date'] = pd.date_range(start='2022-01-01', periods=len(df), freq='D')

df['Date'] = pd.to_datetime(df['Date'])

possible_targets = ['Sales_Forecast', 'Sales', 'Revenue', 'Units_Sold']

target = None
for col in possible_targets:
    if col in df.columns:
        target = col
        break

if target is None:
    # fallback: last numeric column
    numeric_cols = df.select_dtypes(include=['number']).columns
    target = numeric_cols[-1]

print("✅ Target column used:", target)

df = df.dropna()
df = df.drop_duplicates()

plt.figure(figsize=(10,5))
plt.plot(df['Date'], df[target])
plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel(target)
plt.show()

df_numeric = df.select_dtypes(include=['number'])

plt.figure(figsize=(8,6))
sns.heatmap(df_numeric.corr(), annot=True, fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year
df['DayOfWeek'] = df['Date'].dt.dayofweek

df['Is_Weekend'] = (df['DayOfWeek'] >= 5).astype(int)

def get_season(month):
    if month in [12,1,2]:
        return 'Winter'
    elif month in [3,4,5]:
        return 'Summer'
    elif month in [6,7,8]:
        return 'Monsoon'
    else:
        return 'Autumn'

df['Season'] = df['Month'].apply(get_season)

df = pd.get_dummies(df, columns=['Season'], drop_first=True)

# Remove Date if still present
if 'Date' in df.columns:
    X = df.drop([target, 'Date'], axis=1)
else:
    X = df.drop([target], axis=1)

y = df[target]

# 🔥 FIX: Convert categorical to numeric
X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Sample Predictions:", y_pred[:5])

from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted")
plt.show()

future_dates = pd.date_range(start=df['Date'].max(), periods=90)

future_df = pd.DataFrame({'Date': future_dates})

future_df['Day'] = future_df['Date'].dt.day
future_df['Month'] = future_df['Date'].dt.month
future_df['Year'] = future_df['Date'].dt.year
future_df['DayOfWeek'] = future_df['Date'].dt.dayofweek
future_df['Is_Weekend'] = (future_df['DayOfWeek'] >= 5).astype(int)

future_df['Season'] = future_df['Month'].apply(get_season)

future_df = pd.get_dummies(future_df, columns=['Season'], drop_first=True)

# Align columns
future_df = future_df.reindex(columns=X.columns, fill_value=0)

future_df['Predicted_Sales'] = model.predict(future_df)

future_df.head()